In [2]:
import numpy as np
print(np.__version__)

2.3.2


# Exercise 1: Array Creation and Manipulation

In [6]:
# Create a 1D NumPy array containing numbers from 0 to 9
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Exercise 2: Type Conversion and Array Operations

In [5]:
# Convert List to Numpy Array with Dtype Int
list1 = [3.14, 2.17, 0, 1, 2]

list1 = np.array(list1, dtype=int)
list1

array([3, 2, 0, 1, 2])

# Exercise 3 : Working with Multi-Dimensional Arrays

In [7]:
# Create a 3x3 NumPy array with values ranging from 1 to 9
array = np.arange(1, 10).reshape(3, 3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Exercise 4: Creating Multi-Dimensional Array with Random Numbers

In [10]:
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.
rand_array = np.random.rand(4,5)
rand_array

array([[0.56274697, 0.42256279, 0.07439396, 0.72711077, 0.75752173],
       [0.17085148, 0.81940342, 0.26011686, 0.10264375, 0.40910002],
       [0.67754138, 0.62802613, 0.1353075 , 0.8076217 , 0.49170697],
       [0.49103982, 0.66210235, 0.95511538, 0.80967172, 0.04683661]])

# Exercise 5: Indexing Arrays

In [13]:
# Select the 2nd Row from a Given 2d Array
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

print("Second Row:", array[1, :])

Second Row: [20 21 22 23 24]


# Exercise 6: Reversing Elements

In [ ]:
# Reverse the order of elements in a given 1D NumPy array (first element becomes last)
array = np.arange(10)
array = array[::-1]
array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Exercise 7 : Identity Matrix

In [19]:
# Create a 4x4 identity matrix using NumPy
imatrix = np.identity(4)
imatrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Exercise 8: Simple Aggregate Functions

In [20]:
# Find the sum and average of a given 1D array
array = np.arange(10)
print("Sum:", np.sum(array))
print("Average:", np.mean(array))

Sum: 45
Average: 4.5


# Exercise 9: Create Array and Change its Structure

In [23]:
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix
array = np.arange(1,21).reshape(4,5)
array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Exercise 10: Conditional Selection of Values

In [24]:
# Extract all odd numbers from a given NumPy array
array = np.arange(10)
print(array[array % 2 == 1])

[1 3 5 7 9]
