In [6]:
import numpy as np

In [7]:
print(np.__version__)

2.3.2


In [8]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3d)

1D Array: [1 2 3 4]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:

# Array attributes
print("Shape:", array_3d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 2, 2)
Size: 6
Data Type: int64


In [13]:
array_1d = np.array([1, 2, 3, 4])
# Output: 1D Array: [1 2 3 4], Shape: (4,), Size: 4
array_1d

array([1, 2, 3, 4])

In [14]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array_2d.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.shape)



(2, 2, 2)


In [18]:
np.zeros((3, 2))  # 3 rows, 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((2, 3), dtype=int)



array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
arr1 = np.arange(1, 11, dtype=float)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Exercise: Exploring NumPy Arrays

In [34]:
# 1
arr = np.arange(1, 6, dtype=int)

arr1 = np.arange(1, 7, dtype=int)
arr1 = arr1.reshape(2,3)
arr1

# 2
print(arr.shape)
print(arr.size)
print(arr.dtype)
print()
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

# 3
arr2 = np.arange(1, 4, dtype=float)
print(arr2)

(5,)
5
int64

(2, 3)
6
int64
[1. 2. 3.]


Exercise: Create the following arrays:

In [52]:
# A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [54]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:\n", array_2d[0:2, 1:3])

Slice of the array:
 [[2 3]
 [5 6]]


In [56]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)

Result of Boolean Indexing: [4 5 6]


In [57]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [58]:
# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

Elements greater than 25: [30 40 50]
Select specific elements: [20 40]


Exercise: Practicing Indexing and Slicing

In [ ]:
array = np.arange(1, 11)
print(array[4])

# Elements 3 - 8
print(array[2:8])

# Create an array with 6 random numbers between 10 and 50
rand = np.random.randint(low=10, high=50, size=6)
print(rand)

# Elements greater than 30
print(rand[rand > 30])

# Fancy Indexing: 2nd, 4th, 6th elements
print(rand[[1,3,5]])

5
[3 4 5 6 7 8]
[21 10 35 29 18 36]
[35 36]
[10 29 36]


In [82]:
rand = np.random.randint(10, 50, 6)
print(rand)
print(rand[rand>30])

[21 13 14 45 21 12]
[45]


In [94]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([1, 7, 4, 2, 5, 3, 6])

In [104]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[1, 2],
       [5, 6],
       [3, 4]])

In [105]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10
arr

array([ 1,  2, 10,  4,  5])

In [108]:
arr[1:4] = [20, 30, 40]
print(arr)

[ 1 20 30 40  5]


In [109]:
arr[arr > 10] = 100
print(arr)

[  1 100 100 100   5]


In [110]:
arr[np.array([1, 3])] = 500
print(arr)

[  1 500 100 500   5]


In [111]:
sub_arr = arr[1:3]
sub_arr[0] = 600
print(sub_arr)

[600 100]


Exercises on Indexing and Slicing for Array Modification

In [ ]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Element-wise multiplication
print("Multiplication:", a * b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Broadcasting with scalar: [3 6 9]


In [118]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b
subtraction = a - b

print("1D Array:\n", a)
print("2D Array:\n", b)
print("Broadcasted Addition:\n", result)
print("Broacasted Subtraction:\n", subtraction)

1D Array:
 [0 1 2]
2D Array:
 [[0 1 2]
 [3 4 5]]
Broadcasted Addition:
 [[0 2 4]
 [3 5 7]]
Broacasted Subtraction:
 [[ 0  0  0]
 [-3 -3 -3]]


In [117]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [122]:
import numpy as np

# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

a = a.reshape(3,2)
result = a + b
print("Addition After Reshape:\n", result)

Error: operands could not be broadcast together with shapes (2,3) (2,) 
Addition After Reshape:
 [[2 4]
 [4 6]
 [6 8]]


In [125]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array:\n", a)
print("\n1D Array:\n", b)
print("\nBroadcasted Multiplication:\n", result)

2D Array:
 [[1 2 3]
 [4 5 6]]

1D Array:
 [1 2 3]

Broadcasted Multiplication:
 [[ 1  4  9]
 [ 4 10 18]]


In [126]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


Exercise: Basic Operations with Arrays

In [133]:
# Arithmetic Operations: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.
a = np.array([2,4,6])
b = np.array([2,2,2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

# Aggregation Functions: For the arrays created above, find the sum, mean, minimum, and maximum of each array.
print("Means")
print(np.mean(a), np.mean(b))
print("\nSums")
print(np.sum(a), np.sum(b))
print('\nMins')
print(np.min(a), np.min(b))
print("\nMax")
print(np.max(a), np.max(b))

# Broadcasting with Scalar: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.

[4 6 8]
[0 2 4]
[ 4  8 12]
[1. 2. 3.]
Means
4.0 2.0

Sums
12 6

Mins
2 2

Max
6 2


In [134]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9
print("1D Array:", array)
# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

1D Array: [1 2 3 4 5 6 7 8 9]
Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [135]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise: Reshaping and Transposing Arrays

In [ ]:
# Reshape Array
array_1d = np.arange(12)

# 4x3 Matrix
array_reshaped = array_1d.reshape(4,3)
print(array_reshaped)

# 2x6 Matrix
array_reshaped = array_1d.reshape(2,6)
print('\n', array_reshaped)

# Transpose
transposed_array = array_reshaped.T
print('\n', transposed_array)

# Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.
my_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('\n', my_array)

my_array_transposed = my_array.T
print('\n', my_array_transposed)

my_array_reshaped = my_array_transposed.reshape(12,)
print('\n', my_array_reshaped)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

 [ 1  5  9  2  6 10  3  7 11  4  8 12]


In [136]:
# Reshaping data for machine learning model
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each
data

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [137]:
# Preparing data for heatmap visualization
matrix = np.random.rand(10, 10)
print(matrix)
reshaped_matrix = matrix.reshape(5, 20)  # Reshaping for a different visual representation
reshaped_matrix

[[0.58496067 0.36419245 0.98616097 0.0899767  0.42964386 0.20408646
  0.80240197 0.26361494 0.40896871 0.76556018]
 [0.80940219 0.96679123 0.02116518 0.02959532 0.10086186 0.01679069
  0.35722682 0.58429727 0.0653239  0.88419172]
 [0.81732463 0.59838487 0.29105198 0.07576416 0.22477456 0.58156568
  0.93788816 0.85319302 0.32273791 0.19133027]
 [0.7294679  0.81167687 0.18046201 0.36835354 0.29842171 0.61042048
  0.15406498 0.40370238 0.83272039 0.33783581]
 [0.05105478 0.32436012 0.11781722 0.53515084 0.86205507 0.29323882
  0.70120341 0.07560209 0.88996787 0.59659491]
 [0.22117258 0.21002688 0.00153843 0.69178528 0.76182599 0.39562142
  0.1938689  0.35374074 0.89314331 0.58203225]
 [0.10249652 0.63565581 0.17876877 0.32639416 0.49047831 0.57629761
  0.90438528 0.69606787 0.55724442 0.07493912]
 [0.94286399 0.08004968 0.29108073 0.95480454 0.20083396 0.27872048
  0.53440839 0.57457411 0.53272674 0.7407465 ]
 [0.47049638 0.28618022 0.23446978 0.18433328 0.23633472 0.23051951
  0.45775894

array([[0.58496067, 0.36419245, 0.98616097, 0.0899767 , 0.42964386,
        0.20408646, 0.80240197, 0.26361494, 0.40896871, 0.76556018,
        0.80940219, 0.96679123, 0.02116518, 0.02959532, 0.10086186,
        0.01679069, 0.35722682, 0.58429727, 0.0653239 , 0.88419172],
       [0.81732463, 0.59838487, 0.29105198, 0.07576416, 0.22477456,
        0.58156568, 0.93788816, 0.85319302, 0.32273791, 0.19133027,
        0.7294679 , 0.81167687, 0.18046201, 0.36835354, 0.29842171,
        0.61042048, 0.15406498, 0.40370238, 0.83272039, 0.33783581],
       [0.05105478, 0.32436012, 0.11781722, 0.53515084, 0.86205507,
        0.29323882, 0.70120341, 0.07560209, 0.88996787, 0.59659491,
        0.22117258, 0.21002688, 0.00153843, 0.69178528, 0.76182599,
        0.39562142, 0.1938689 , 0.35374074, 0.89314331, 0.58203225],
       [0.10249652, 0.63565581, 0.17876877, 0.32639416, 0.49047831,
        0.57629761, 0.90438528, 0.69606787, 0.55724442, 0.07493912,
        0.94286399, 0.08004968, 0.29108073, 0

In [139]:
# Transposing for matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
product = A.dot(B.transpose())  # Transposing B to make multiplication possible
product

array([17, 39])

In [141]:
# Aggregating data after reshaping
data = np.random.rand(6, 2)
print(data)
reshaped_data = data.reshape(3, 4)
print('\n', reshaped_data)
mean_values = np.mean(reshaped_data, axis=1)  # Mean of each reshaped group
mean_values

[[0.00629567 0.56483624]
 [0.49540283 0.21340218]
 [0.32356707 0.02349041]
 [0.28414297 0.88789025]
 [0.58101345 0.95404482]
 [0.76472611 0.92222248]]

 [[0.00629567 0.56483624 0.49540283 0.21340218]
 [0.32356707 0.02349041 0.28414297 0.88789025]
 [0.58101345 0.95404482 0.76472611 0.92222248]]


array([0.31998423, 0.37977268, 0.80550171])

In [142]:
# Organizing data for feature selection
data = np.random.rand(100, 10)  # 100 observations, 10 features
reshaped_data = data.reshape(100, 5, 2)  # Grouping features for analysis
reshaped_data

array([[[2.18550626e-01, 4.20633498e-02],
        [8.75503686e-01, 2.07595668e-01],
        [1.99836630e-01, 9.41456786e-01],
        [6.07054436e-01, 7.71924235e-01],
        [5.52317217e-01, 4.58151192e-02]],

       [[7.60267335e-01, 2.93948152e-01],
        [2.40110944e-01, 9.43409774e-01],
        [6.82521496e-01, 7.83517195e-01],
        [8.86248383e-01, 1.49420370e-02],
        [8.73488115e-01, 9.55383432e-02]],

       [[6.13378752e-02, 7.11645496e-01],
        [1.52734489e-01, 3.21482109e-01],
        [4.01498162e-01, 3.21683069e-01],
        [5.18341083e-01, 7.64908302e-01],
        [5.81880512e-01, 4.11647496e-01]],

       [[6.63715290e-01, 6.63366223e-01],
        [6.45904883e-01, 8.40971957e-01],
        [1.62928185e-01, 3.35629876e-01],
        [2.10482004e-01, 3.53775113e-01],
        [6.45283796e-01, 2.42424516e-02]],

       [[3.13728496e-01, 3.06988073e-01],
        [4.16054009e-01, 8.37031496e-01],
        [5.04933655e-01, 2.73376828e-01],
        [9.29957423e-01, 2

In [143]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
# or
#t = a @ b #dot product
result

np.int64(32)

In [144]:

# Reshaping data for time-series analysis
time_series_data = np.random.rand(365)  # Daily data for a year
#reshaped_for_analysis = time_series_data.reshape(52, 7)  # Weekly data, 7 days a week
reshaped_for_analysis = time_series_data[:364].reshape(52, 7)
reshaped_for_analysis

array([[0.16595162, 0.85937626, 0.02677293, 0.08209604, 0.66059617,
        0.49161093, 0.65848761],
       [0.47033599, 0.05609042, 0.62047148, 0.80666794, 0.2007274 ,
        0.29764415, 0.39208982],
       [0.42903761, 0.12742478, 0.38526943, 0.36477346, 0.14403062,
        0.05096435, 0.22563432],
       [0.84116731, 0.85155015, 0.97392041, 0.66289234, 0.19476298,
        0.55094313, 0.95798373],
       [0.4388117 , 0.61622584, 0.94512207, 0.1956413 , 0.18792754,
        0.95771104, 0.18127545],
       [0.50247054, 0.19982629, 0.62620456, 0.81564212, 0.79853689,
        0.61259346, 0.28031164],
       [0.06782942, 0.69902651, 0.37260535, 0.17142002, 0.79795162,
        0.4587653 , 0.03865699],
       [0.04753555, 0.36072711, 0.24919468, 0.72682192, 0.34806309,
        0.53583565, 0.56161418],
       [0.3036271 , 0.71039244, 0.61470315, 0.24190946, 0.90683236,
        0.76891693, 0.64997516],
       [0.18038015, 0.65758468, 0.1100992 , 0.73149539, 0.76448057,
        0.72969681, 0.8