In [2]:
import numpy as np
print(np.__version__)

2.3.2


# Exercise 1 : Minimum and Maximum of Random Array

In [20]:
# Create a 5x5 array with random values and find the minimum and maximum values.
array = np.random.rand(5,5)
print(f"Min: {np.min(array)}, Max: {np.max(array)}")

Min: 0.0370838109187992, Max: 0.944570487920368


# Exercise 2 : Matrix Normalization

In [27]:
# Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).
# Create 3x3 Matrix with Random Integers between 1 and 10
array = np.random.randint(1,10,(3,3))

# Calculate Mean/Std. Dev of the Array
mean = np.mean(array)
se = np.std(array)

# Normalize the Array with the Calculated Variables
array = (array - mean) / se

print(f"mean: {np.mean(array)}\nStd. Dev: {np.std(array)}")

mean: -9.868649107779169e-17
Std. Dev: 1.0


# Exercise 3: Evenly Spaced Elements in Array

In [29]:
# Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive
array = np.linspace(0, 10, 50, endpoint=False)
array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

# Exercise 4 : Matrix Multiplication

* For Matrix Multiplication: The Number of Columns in the First Matrix must equal the Number of Rows in the Second Matrix.
* The Output Matrix's Dimensions Will be equal to The Number of Rows of the First by the Number of Columns of the Second

In [54]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
# 5x3 Matrix
a = np.random.randint(1, 100, (5, 3))

# 3x2 Matrix
b = np.random.randint(1, 100, (3, 2))

# Matrix Multiplication
result = a @ b
print(result)

[[ 5380  6187]
 [10299  9227]
 [12286 12755]
 [ 3699  4611]
 [ 5205  5497]]


# Exercise 5: 

In [ ]:
# Create two matrices of compatible dimensions.
a = np.random.rand(4, 7)
b = np.random.rand(7, 3)
print(a, '\n')
print(b)

# Perform matrix multiplication on these matrices and display the result.
result = a @ b
print('\n', result) # 4x3 Matrix

[[0.08741037 0.95669868 0.87703897 0.15609974 0.1528703  0.37579554
  0.12580124]
 [0.87488335 0.90905377 0.05423199 0.93073382 0.87772982 0.82854321
  0.66099383]
 [0.13688598 0.40732828 0.94093502 0.31615559 0.14523326 0.16807874
  0.52847698]
 [0.01924654 0.67736666 0.10935661 0.37297207 0.13502291 0.6687849
  0.24162364]] 

[[0.70396401 0.6282785  0.34493234]
 [0.04513405 0.99941571 0.64252724]
 [0.00702188 0.74737966 0.38334788]
 [0.04415653 0.2128969  0.89941071]
 [0.19746859 0.0911425  0.21045958]
 [0.99303522 0.62944057 0.56701145]
 [0.54064111 0.85731452 0.53380245]]

 [[0.58914334 2.05809714 1.43387083]
 [2.05185156 2.86507205 2.75112932]
 [0.61661814 1.83574053 1.36196569]
 [0.88277964 1.49061271 1.35584685]]


In [60]:
np.random.random((3, 4))

array([[0.30858511, 0.41197905, 0.02893098, 0.89520541],
       [0.58204713, 0.41172391, 0.41388304, 0.72392689],
       [0.30503475, 0.05990835, 0.30719476, 0.8334448 ]])

In [61]:
np.random.rand(3,4)

array([[0.41637385, 0.5673734 , 0.27427078, 0.68454466],
       [0.92811896, 0.99561276, 0.60402568, 0.88181462],
       [0.99279257, 0.3667112 , 0.33743734, 0.15398343]])